### ISSUE TITLE
costcla incompatible with latest version of Scikit-Learn 

### ISSUE THREAD

**Issue by guruprad** [albahnsen/CostSensitiveClassification#22]
It seems that scikit-learn versions 0.21 and above have deprecated and removed _sklearn.externals.six_ and _sklearn.externals.joblib_ according to this release [notes](https://github.com/scikit-learn/scikit-learn/blob/c4733f4895c1becdf587b38970f6f7066656e3f9/doc/whats_new/v0.21.rst). Is there any plans to accommodate this change or raise this issue in the setup.py script (as of now the sklearn requirements are explicitly listed as 'scikit-learn>=0.15.0b2')? I can also take a stab at creating a PR for this issue but am unaware of the etiquette and guidelines. Furthermore, I notice there is a lack of automated testing so I am unsure if I would break something :D .

**Comment by albahnsen** [comment]
yes indeed we need to solve this. if you can do the PR I will appreciated.

**Comment by BingeCode** [comment]
I found the issue and have a fix ready in my cloned repo. I have never contributed to an open source project, though, and was not able to figure out how to push the changes in my local branch '22_incompatible_scikit_learn' or how to create the PR. Seems like I don't have permissions.

It's just a fix of imports in two files.
- In .\costcla\models\cost_tree.py change `from sklearn.externals import six` to `import six`
- In .\costcla\models\bagging.py change ALL `from sklearn.externals.joblib import` to `from joblib import`

After this, everything works for me so far, but a FutureWarning persists:

> FutureWarning: The sklearn.ensemble.base module is  deprecated in version 0.22 and will be removed in version 0.24. The
> corresponding classes / functions should instead be imported from sklearn.ensemble. 
> Anything that cannot be imported from sklearn.ensemble is now part of the private API.

This can be fixed in .\costcla\models\bagging.py change as well by changing `from sklearn.ensemble.base import` to `from sklearn.ensemble import`

Errors **unrelated** to the imports remain, but that should be looked into by someone more experienced than me :P

Hope this helps others like me who need to use this package for their work / academic studies.

**Comment by BingeCode** [comment]
Btw, @albahnsen similar fixes would need to be done in the pyea package, which I could do, if I had the right permissions/knowledge how to push my changes.

**Comment by albahnsen** [comment]
@BingeCode thank you so much for the help. to push the changes you can, fork the repository, make the changes to your repository, then on github click on pull request (from your fork or copy of the repository), It is simple after you do it the first time.
Again thank you for the interest in helping with this project.

**Comment by BingeCode** [comment]
@albahnsen thanks for the heads up. I created the pull request that fixes the aforementioned errors.

**Comment by albahnsen** [comment]
Excelent work, thank you so much. I already merged the PR.
